### ISSUE TITLE
TypeError: Plugin "plugin-example" is resolving to a different Babel version than what is performing the transformation.

### ISSUE THREAD

**Issue by Dignifiedquire** [sebmck/babel-plugin-example#4]
Hey, I'm trying to get this sample plugin to run, but it fails with this error message:

```
~/play/babel-plugins
❯ node node_modules/babel/bin/babel --plugins babel-plugin-example script.js
/Users/dignifiedquire/play/babel-plugins/node_modules/babel/lib/babel/util.js:55
      throw err;
            ^
TypeError: Plugin "plugin-example" is resolving to a different Babel version than what is performing the transformation.
    at Plugin.buildPass (/Users/dignifiedquire/play/babel-plugins/node_modules/babel-plugin-example/node_modules/babel-core/lib/transformation/plugin.js:121:13)
    at PluginManager.add (/Users/dignifiedquire/play/babel-plugins/node_modules/babel/node_modules/babel-core/lib/transformation/file/plugin-manager.js:216:55)
    at File.buildTransformers (/Users/dignifiedquire/play/babel-plugins/node_modules/babel/node_modules/babel-core/lib/transformation/file/index.js:236:21)
    at new File (/Users/dignifiedquire/play/babel-plugins/node_modules/babel/node_modules/babel-core/lib/transformation/file/index.js:136:10)
    at Pipeline.transform (/Users/dignifiedquire/play/babel-plugins/node_modules/babel/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Object.exports.transform (/Users/dignifiedquire/play/babel-plugins/node_modules/babel/lib/babel/util.js:40:22)
    at Object.exports.compile (/Users/dignifiedquire/play/babel-plugins/node_modules/babel/lib/babel/util.js:49:20)
    at /Users/dignifiedquire/play/babel-plugins/node_modules/babel/lib/babel/file.js:123:23
    at arrayEach (/Users/dignifiedquire/play/babel-plugins/node_modules/babel/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/Users/dignifiedquire/play/babel-plugins/node_modules/babel/node_modules/lodash/index.js:3345:13)
```

```js
// script.js
function helloWorld () {
  return 'hello world'
}
```

## System Details

```
~/play/babel-plugins
❯ node -v
v2.3.3

~/play/babel-plugins
❯ npm -v
2.12.1

~/play/babel-plugins
❯ npm ls
/Users/dignifiedquire/play/babel-plugins
├─┬ babel@5.8.3
│ ├─┬ babel-core@5.8.3
│ │ ├── babel-plugin-constant-folding@1.0.1
│ │ ├── babel-plugin-dead-code-elimination@1.0.2
│ │ ├── babel-plugin-eval@1.0.1
│ │ ├── babel-plugin-inline-environment-variables@1.0.1
│ │ ├── babel-plugin-jscript@1.0.3
│ │ ├── babel-plugin-member-expression-literals@1.0.1
│ │ ├── babel-plugin-property-literals@1.0.1
│ │ ├── babel-plugin-proto-to-assign@1.0.3
│ │ ├── babel-plugin-react-constant-elements@1.0.3
│ │ ├── babel-plugin-react-display-name@1.0.3
│ │ ├── babel-plugin-remove-console@1.0.1
│ │ ├── babel-plugin-remove-debugger@1.0.1
│ │ ├── babel-plugin-runtime@1.0.7
│ │ ├─┬ babel-plugin-undeclared-variables-check@1.0.2
│ │ │ └── leven@1.0.2
│ │ ├── babel-plugin-undefined-to-void@1.1.6
│ │ ├── babylon@5.8.3
│ │ ├── bluebird@2.9.34
│ │ ├─┬ chalk@1.1.0
│ │ │ ├── ansi-styles@2.1.0
│ │ │ ├── escape-string-regexp@1.0.3
│ │ │ ├─┬ has-ansi@2.0.0
│ │ │ │ └── ansi-regex@2.0.0
│ │ │ ├─┬ strip-ansi@3.0.0
│ │ │ │ └── ansi-regex@2.0.0
│ │ │ └── supports-color@2.0.0
│ │ ├── core-js@0.9.18
│ │ ├─┬ debug@2.2.0
│ │ │ └── ms@0.7.1
│ │ ├─┬ detect-indent@3.0.1
│ │ │ ├── get-stdin@4.0.1
│ │ │ └── minimist@1.1.2
│ │ ├── esutils@2.0.2
│ │ ├── globals@6.4.1
│ │ ├─┬ home-or-tmp@1.0.0
│ │ │ ├── os-tmpdir@1.0.1
│ │ │ └── user-home@1.1.1
│ │ ├─┬ is-integer@1.0.4
│ │ │ ├─┬ is-finite@1.0.1
│ │ │ │ └── number-is-nan@1.0.0
│ │ │ └─┬ is-nan@1.1.0
│ │ │   └─┬ define-properties@1.1.1
│ │ │     ├── foreach@2.0.5
│ │ │     └── object-keys@1.0.7
│ │ ├── js-tokens@1.0.1
│ │ ├─┬ line-numbers@0.2.0
│ │ │ └── left-pad@0.0.3
│ │ ├─┬ minimatch@2.0.10
│ │ │ └─┬ brace-expansion@1.1.0
│ │ │   ├── balanced-match@0.2.0
│ │ │   └── concat-map@0.0.1
│ │ ├── private@0.1.6
│ │ ├─┬ regenerator@0.8.34
│ │ │ ├─┬ commoner@0.10.3
│ │ │ │ ├── commander@2.5.1
│ │ │ │ ├─┬ glob@4.2.2
│ │ │ │ │ ├─┬ inflight@1.0.4
│ │ │ │ │ │ └── wrappy@1.0.1
│ │ │ │ │ ├── inherits@2.0.1
│ │ │ │ │ ├─┬ minimatch@1.0.0
│ │ │ │ │ │ ├── lru-cache@2.6.5
│ │ │ │ │ │ └── sigmund@1.0.1
│ │ │ │ │ └─┬ once@1.3.2
│ │ │ │ │   └── wrappy@1.0.1
│ │ │ │ ├── graceful-fs@3.0.8
│ │ │ │ ├── iconv-lite@0.4.11
│ │ │ │ ├── install@0.1.8
│ │ │ │ ├─┬ mkdirp@0.5.1
│ │ │ │ │ └── minimist@0.0.8
│ │ │ │ └── q@1.1.2
│ │ │ ├─┬ defs@1.1.0
│ │ │ │ ├─┬ alter@0.2.0
│ │ │ │ │ └── stable@0.1.5
│ │ │ │ ├── ast-traverse@0.1.1
│ │ │ │ ├── breakable@1.0.0
│ │ │ │ ├── esprima-fb@8001.1001.0-dev-harmony-fb
│ │ │ │ ├── simple-fmt@0.1.0
│ │ │ │ ├── simple-is@0.2.0
│ │ │ │ ├── stringmap@0.2.2
│ │ │ │ ├── stringset@0.2.1
│ │ │ │ ├── tryor@0.1.2
│ │ │ │ └── yargs@1.3.3
│ │ │ ├── esprima-fb@13001.1.0-dev-harmony-fb
│ │ │ ├─┬ recast@0.10.18
│ │ │ │ ├── ast-types@0.8.2
│ │ │ │ └── esprima-fb@14001.1.0-dev-harmony-fb
│ │ │ └── through@2.3.8
│ │ ├─┬ regexpu@1.2.0
│ │ │ ├─┬ recast@0.10.21
│ │ │ │ ├── ast-types@0.8.3
│ │ │ │ └── esprima-fb@15001.1.0-dev-harmony-fb
│ │ │ ├── regenerate@1.2.1
│ │ │ ├── regjsgen@0.2.0
│ │ │ └─┬ regjsparser@0.1.4
│ │ │   └── jsesc@0.5.0
│ │ ├─┬ repeating@1.1.3
│ │ │ └─┬ is-finite@1.0.1
│ │ │   └── number-is-nan@1.0.0
│ │ ├── resolve@1.1.6
│ │ ├── shebang-regex@1.0.0
│ │ ├─┬ source-map-support@0.2.10
│ │ │ └─┬ source-map@0.1.32
│ │ │   └── amdefine@1.0.0
│ │ ├── strip-json-comments@1.0.2
│ │ ├── to-fast-properties@1.0.1
│ │ └── trim-right@1.0.1
│ ├─┬ chokidar@1.0.5
│ │ ├─┬ anymatch@1.3.0
│ │ │ └─┬ micromatch@2.2.0
│ │ │   ├─┬ arr-diff@1.0.1
│ │ │   │ └── array-slice@0.2.3
│ │ │   ├── array-unique@0.2.1
│ │ │   ├─┬ braces@1.8.0
│ │ │   │ ├─┬ expand-range@1.8.1
│ │ │   │ │ └─┬ fill-range@2.2.2
│ │ │   │ │   ├── is-number@1.1.2
│ │ │   │ │   ├── isobject@1.0.2
│ │ │   │ │   ├── randomatic@1.1.0
│ │ │   │ │   └── repeat-string@1.5.2
│ │ │   │ ├── preserve@0.2.0
│ │ │   │ └── repeat-element@1.1.2
│ │ │   ├── expand-brackets@0.1.2
│ │ │   ├─┬ extglob@0.3.0
│ │ │   │ └── is-extglob@1.0.0
│ │ │   ├── filename-regex@2.0.0
│ │ │   ├── kind-of@1.1.0
│ │ │   ├─┬ object.omit@1.1.0
│ │ │   │ ├─┬ for-own@0.1.3
│ │ │   │ │ └── for-in@0.1.4
│ │ │   │ └── isobject@1.0.2
│ │ │   ├─┬ parse-glob@3.0.2
│ │ │   │ ├── glob-base@0.2.0
│ │ │   │ ├── is-dotfile@1.0.1
│ │ │   │ └── is-extglob@1.0.0
│ │ │   └─┬ regex-cache@0.4.2
│ │ │     ├── is-equal-shallow@0.1.3
│ │ │     └── is-primitive@2.0.0
│ │ ├── arrify@1.0.0
│ │ ├── async-each@0.1.6
│ │ ├─┬ fsevents@0.3.6
│ │ │ └── nan@1.8.4
│ │ ├── glob-parent@1.2.0
│ │ ├─┬ is-binary-path@1.0.1
│ │ │ └── binary-extensions@1.3.1
│ │ ├── is-glob@1.1.3
│ │ └─┬ readdirp@1.4.0
│ │   ├── graceful-fs@4.1.2
│ │   ├─┬ minimatch@0.2.14
│ │   │ ├── lru-cache@2.6.5
│ │   │ └── sigmund@1.0.1
│ │   └─┬ readable-stream@1.0.33
│ │     ├── core-util-is@1.0.1
│ │     ├── inherits@2.0.1
│ │     ├── isarray@0.0.1
│ │     └── string_decoder@0.10.31
│ ├─┬ commander@2.8.1
│ │ └── graceful-readlink@1.0.1
│ ├── convert-source-map@1.1.1
│ ├── fs-readdir-recursive@0.1.2
│ ├─┬ glob@5.0.14
│ │ ├─┬ inflight@1.0.4
│ │ │ └── wrappy@1.0.1
│ │ ├── inherits@2.0.1
│ │ ├─┬ minimatch@2.0.10
│ │ │ └─┬ brace-expansion@1.1.0
│ │ │   ├── balanced-match@0.2.0
│ │ │   └── concat-map@0.0.1
│ │ └─┬ once@1.3.2
│ │   └── wrappy@1.0.1
│ ├── lodash@3.10.0
│ ├─┬ output-file-sync@1.1.1
│ │ ├─┬ mkdirp@0.5.1
│ │ │ └── minimist@0.0.8
│ │ └── xtend@4.0.0
│ ├── path-exists@1.0.0
│ ├── path-is-absolute@1.0.0
│ ├── slash@1.0.0
│ └─┬ source-map@0.4.4
│   └── amdefine@1.0.0
└─┬ babel-plugin-example@1.0.0
  └─┬ babel-core@5.8.3
    ├── babel-plugin-constant-folding@1.0.1
    ├── babel-plugin-dead-code-elimination@1.0.2
    ├── babel-plugin-eval@1.0.1
    ├── babel-plugin-inline-environment-variables@1.0.1
    ├── babel-plugin-jscript@1.0.3
    ├── babel-plugin-member-expression-literals@1.0.1
    ├── babel-plugin-property-literals@1.0.1
    ├── babel-plugin-proto-to-assign@1.0.3
    ├── babel-plugin-react-constant-elements@1.0.3
    ├── babel-plugin-react-display-name@1.0.3
    ├── babel-plugin-remove-console@1.0.1
    ├── babel-plugin-remove-debugger@1.0.1
    ├── babel-plugin-runtime@1.0.7
    ├─┬ babel-plugin-undeclared-variables-check@1.0.2
    │ └── leven@1.0.2
    ├── babel-plugin-undefined-to-void@1.1.6
    ├── babylon@5.8.3
    ├── bluebird@2.9.34
    ├─┬ chalk@1.1.0
    │ ├── ansi-styles@2.1.0
    │ ├── escape-string-regexp@1.0.3
    │ ├─┬ has-ansi@2.0.0
    │ │ └── ansi-regex@2.0.0
    │ ├─┬ strip-ansi@3.0.0
    │ │ └── ansi-regex@2.0.0
    │ └── supports-color@2.0.0
    ├── convert-source-map@1.1.1
    ├── core-js@0.9.18
    ├─┬ debug@2.2.0
    │ └── ms@0.7.1
    ├─┬ detect-indent@3.0.1
    │ ├── get-stdin@4.0.1
    │ └── minimist@1.1.2
    ├── esutils@2.0.2
    ├── fs-readdir-recursive@0.1.2
    ├── globals@6.4.1
    ├─┬ home-or-tmp@1.0.0
    │ ├── os-tmpdir@1.0.1
    │ └── user-home@1.1.1
    ├─┬ is-integer@1.0.4
    │ ├─┬ is-finite@1.0.1
    │ │ └── number-is-nan@1.0.0
    │ └─┬ is-nan@1.1.0
    │   └─┬ define-properties@1.1.1
    │     ├── foreach@2.0.5
    │     └── object-keys@1.0.7
    ├── js-tokens@1.0.1
    ├─┬ line-numbers@0.2.0
    │ └── left-pad@0.0.3
    ├── lodash@3.10.0
    ├─┬ minimatch@2.0.10
    │ └─┬ brace-expansion@1.1.0
    │   ├── balanced-match@0.2.0
    │   └── concat-map@0.0.1
    ├─┬ output-file-sync@1.1.1
    │ ├─┬ mkdirp@0.5.1
    │ │ └── minimist@0.0.8
    │ └── xtend@4.0.0
    ├── path-exists@1.0.0
    ├── path-is-absolute@1.0.0
    ├── private@0.1.6
    ├─┬ regenerator@0.8.34
    │ ├─┬ commoner@0.10.3
    │ │ ├── commander@2.5.1
    │ │ ├─┬ glob@4.2.2
    │ │ │ ├─┬ inflight@1.0.4
    │ │ │ │ └── wrappy@1.0.1
    │ │ │ ├── inherits@2.0.1
    │ │ │ ├─┬ minimatch@1.0.0
    │ │ │ │ ├── lru-cache@2.6.5
    │ │ │ │ └── sigmund@1.0.1
    │ │ │ └─┬ once@1.3.2
    │ │ │   └── wrappy@1.0.1
    │ │ ├── graceful-fs@3.0.8
    │ │ ├── iconv-lite@0.4.11
    │ │ ├── install@0.1.8
    │ │ ├─┬ mkdirp@0.5.1
    │ │ │ └── minimist@0.0.8
    │ │ └── q@1.1.2
    │ ├─┬ defs@1.1.0
    │ │ ├─┬ alter@0.2.0
    │ │ │ └── stable@0.1.5
    │ │ ├── ast-traverse@0.1.1
    │ │ ├── breakable@1.0.0
    │ │ ├── esprima-fb@8001.1001.0-dev-harmony-fb
    │ │ ├── simple-fmt@0.1.0
    │ │ ├── simple-is@0.2.0
    │ │ ├── stringmap@0.2.2
    │ │ ├── stringset@0.2.1
    │ │ ├── tryor@0.1.2
    │ │ └── yargs@1.3.3
    │ ├── esprima-fb@13001.1.0-dev-harmony-fb
    │ ├─┬ recast@0.10.18
    │ │ ├── ast-types@0.8.2
    │ │ └── esprima-fb@14001.1.0-dev-harmony-fb
    │ └── through@2.3.8
    ├─┬ regexpu@1.2.0
    │ ├─┬ recast@0.10.21
    │ │ ├── ast-types@0.8.3
    │ │ └── esprima-fb@15001.1.0-dev-harmony-fb
    │ ├── regenerate@1.2.1
    │ ├── regjsgen@0.2.0
    │ └─┬ regjsparser@0.1.4
    │   └── jsesc@0.5.0
    ├─┬ repeating@1.1.3
    │ └─┬ is-finite@1.0.1
    │   └── number-is-nan@1.0.0
    ├── resolve@1.1.6
    ├── shebang-regex@1.0.0
    ├── slash@1.0.0
    ├─┬ source-map@0.4.4
    │ └── amdefine@1.0.0
    ├─┬ source-map-support@0.2.10
    │ └─┬ source-map@0.1.32
    │   └── amdefine@1.0.0
    ├── strip-json-comments@1.0.2
    ├── to-fast-properties@1.0.1
    └── trim-right@1.0.1

```

**Comment by tomaskulich** [comment]
One way how to fix this:
- run `npm dedupe` to make babel-plugin-example use the shared (peer) version of babel
- you must use this (shared) one babel to run the example, i.e. you run it such as:

     `./node_modules/babel/bin/babel.js --plugins babel-plugin-example script.js`

however, maybe there is some more elegant way how to solve this :)

**Comment by sebmck** [comment]
It's because I haven't published the latest version that's in `master`. This repo/project is only a reference and you should just be consulting the code.

**Comment by uadev** [comment]
Could you please publish the latest version or at least provide a workaround?

**Comment by sebmck** [comment]
Why do you need to use this?

**Comment by uadev** [comment]
To develop my own plugin of course.
